
services:
  db:
    image: postgres:12
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: devgrid_web
    env_file:
      - ./app/.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - test

  test:
    image: python:3.11-slim-buster
    container_name: devgrid_test
    depends_on:
      - db
    entrypoint: >
      sh -c "
        apt-get update &&
        apt-get install -y postgresql-client &&
        until pg_isready -h db -p 5432 -U ${POSTGRES_USER}; do
          echo 'Waiting for database...';
          sleep 2;
        done;
        echo 'Database is ready!';
        exit 0
      "
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}

volumes:
  postgres_data:
