[tool.pytest.ini_options]
pythonpath = [
".", "app/"
]
addopts = "--cov=app --cov-report=term-missing"

[tool.isort]
profile = "black"
case_sensitive=true

[tool.pylint.messages_control]
max-line-length = 110
extension-pkg-whitelist = "pydantic"
disable = "C0114, C3001, W0237, W0621, R0903, I1101, W0511, W1203"